version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"

services:
  nginx:
    image: nginx:1.21
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${NGINX_PORT:-80}:80
    depends_on:
      - sparqlist
    logging: *default-logging
    restart: always

  sparqlist:
    image: ghcr.io/dbcls/sparqlist:snapshot-fffa8c9
    environment:
      TZ: Asia/Tokyo
      ADMIN_PASSWORD: ${SPARQLIST_ADMIN_PASSWORD:-changeme}
      SPARQLIST_TOGOVAR_SPARQL: ${SPARQLIST_TOGOVAR_SPARQL:-http://sparql-proxy:3000/proxy/sparql}
    volumes:
      - ${TOGOVAR_MOBILE_SPARQLET}:/app/repository
    logging: *default-logging
    restart: always
